pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {

        stage('Build') {
            steps {
                dir('arun.first.maven') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('arun.first.maven') {
                    bat 'mvn test'
                }
            }
        }
    }

    post {
        always {
            junit 'arun.first.maven/target/surefire-reports/*.xml'
        }
    }
}

