pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {
        stage('Build') {
            steps {
                dir('arun.first.maven') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('arun.first.maven') {
                    bat 'mvn test'
                }
            }
        }
    }
}
